### PR TITLE
Widget responsiveness

### PR DESCRIPTION
**Pull request by patrickkerrypei**

### CODE REVIEW

**Comment by patrickkerrypei** [comment]
Search feature added - I'll open a new request

**Comment by pmeijer** [comment]
OK, nice. I was just reading through..

**Comment by pmeijer** [comment]
In the future you can just remove the assignee and keep committing to the branch (even though the PR is open).

**Comment by pmeijer** [comment]
Actually you can reopen this one..

**Comment by patrickkerrypei** [comment]
Oh okay, I'll remember next time

**Comment by pmeijer** [comment]
Just to confirm, is this one ready to go now?

**Comment by patrickkerrypei** [comment]
Yeah, sorry about that

**Comment by pmeijer** [comment]
No problemo

**Pull request merged**
